### PR TITLE
Reform core-option "preferred aspect ratio"

### PR DESCRIPTION
**Pull request by arakerlu**
Add support for setting aspect ratio such that it's correct when system is in PAL mode. 

It's done by reforming the core-option "preferred aspect ratio" to have three options: "auto", "ntsc" and "pal".
- ntsc forces to always use pixel aspect ratio of ntsc systems (8:7)
 - this option is basically "8:7 PAR" renamed
- pal forces to always use pixel aspect ratio of pal systems (1.3862:1)
- auto selects ntsc or pal depending on the system

Option "4:3" is removed because I don't see any need for it and seems rather arbitrary and redundant - if you want to use it you can set it in frontend/Retroarch.

For the record, the pixel aspect ratio calculations are based on the nesdev article: http://wiki.nesdev.com/w/index.php/Overscan

### CODE REVIEW

**Comment by rdanbrook** [comment]
I am reviewing this and will likely merge soon.

**Comment by Monroe88** [comment]
The 4:3 option was put there because it was [requested](https://github.com/libretro/libretro-fceumm/pull/43#issuecomment-220760983) as an option. It was just a convenience for people who wanted the original behavior while using Core Provided aspect ratio.

**Comment by rdanbrook** [comment]
I'll rewrite it in a way that hopefully makes everyone happy. Not sure when exactly, but soon.

**Comment by arakerlu** [comment]
In a meanwhile I did a new pull request for update where it's just returned to the list of options. So then, in that regard, it works as before.

**Pull request merged**
