### PR TITLE
Switch to CMake for build system

### PR DESCRIPTION
**Pull request by SoapGentoo**
@rdanbrook I've written the CMake-based build system. It finds all the required dependencies. I've only tried it on Linux currently, I'll try it on macOS and Windows later. I think the **one** `CMakeLists.txt` is very simple, succinct and much easier to read than the old `Makefile`. Building also works fine with Ninja for me, which is supposed to succeed Make at some point in the distant future.

While testing, I also fixed some C++ bugs to allow it to compile with GCC 6 on my system. Coding `-std=XYZ` into build systems is bad, unless say, you need C++11 explicitly, as this creates an undue burden on distributions, where we like to keep `-std=XYZ` in sync across the system, due to ABI concerns. Fixing the C++ failures was easy. Remember, left shifting negative signed integers is undefined behaviour (not just in C++, it's always been in C too, from which C++ inherited it).

In order to attach as few warning-disabling flags as possible, I've fixed the const correctness of the code base, such that `-Wno-write-strings` is not needed anymore. Every flag omitted from the build system makes the total system more portable.

Don't merge it just yet, I still want to do some additional tests. Tell me what you think.

### CODE REVIEW

**Comment by rdanbrook** [comment]
It's looking really good so far. There is only one thing I noticed that could be a problem and I may be wrong about it, but I don't see the ability disable GTK+ on Unix builds.

**Comment by SoapGentoo** [comment]
@rdanbrook 

1. Version updated
2. GTK is enabled with `-DENABLE_GTK=ON/OFF` (I switched it to default on at the moment, I can change it if you like).

Last question: is OpenGL really needed? On Linux, it doesn't seem to be needed.

**Comment by rdanbrook** [comment]
You mean including the OpenGL libs in the build process? It is certainly the technology used to display graphics. Although in another project I'm working on (new NES emulator in C) I don't have to specifically link using -lGL, though that may be due to using GLFW and libepoxy there.

**Comment by SoapGentoo** [comment]
@rdanbrook I've come to the conclusion that OpenGL is **not** needed as a direct dependency, as all rendering happens through SDL. I've removed the OpenGL dependency, do you need any other edits?

**Comment by rdanbrook** [comment]
Nope, all looks good. I see you've updated your branch so I'll merge this, and if any edits need to be made later they can be. Thanks so much for the efforts towards this, and also for fixing problems in the core.

**Comment by SoapGentoo** [comment]
@rdanbrook thanks for being open to improvements.

**Comment by fab1o** [comment]
@SoapGentoo Hey, what are the steps to sucessfullly build on MacOS? I created a ticket for an issue I'm having trying to build:  https://github.com/0ldsk00l/nestopia/issues/330

Thanks for your help.

**Comment by rdanbrook** [comment]
Try homebrew, or if you want to do the build by hand you can use the build
script as a reference.

**Comment by SoapGentoo** [comment]
@fab1o CMake has long been removed, nestopia only supports Autotools.

**Pull request merged**
