### PR TITLE
libretro: Add install and uninstall make targets

### PR DESCRIPTION
**Pull request by bochecha**

### CODE REVIEW

**Comment by bochecha** [comment]
@libretro folks, this probably interests you, so your feedback is obviously welcome. :smiley:

**Comment by bentley** [comment]
I would expect them to go to `$(prefix)/lib/libretro`. At least that’s how they’re packaged on OpenBSD and Arch. The FreeBSD package installs cores to `$(prefix)/libexec/libretro`. But I don’t know what is common practice elsewhere.

**Comment by bochecha** [comment]
So first, with this patch, you can specify the install path:

```
$ make install core_installdir=/usr/lib/libretro
```

Wouldn't that work for FreeBSD, OpenBSD and Arch?

Second, I set it to this path because that's [the path I used in gambatte](). And I had used it in gambatte because [that's the path which was used in bsnes](https://github.com/libretro/bsnes-libretro/commit/5367783d35897e2d2a832ba7805ec9f050997a37) and it wasn't even overridable at that time.

With that being said, `$(prefix)/lib/libretro/` seems like the correct path to me. We don't have libretro cores in Fedora, but as a Fedora packager, I think that's where I'd put them.

I'm happy to change that in the patch if you think that's a blocker.

**Comment by rdanbrook** [comment]
I am watching the comments on this pull request, and I am waiting for a consensus. I would like to point out though, that the variable core_installdir should be ALLCAPS for style reasons.

**Comment by bentley** [comment]
>So first, with this patch, you can specify the install path:
>
>$ make install core_installdir=/usr/lib/libretro
>
>Wouldn't that work for FreeBSD, OpenBSD and Arch?

Yes, that’s fine. But the default should be something other than `$(prefix)/lib`, because people and distros will set `libretro_directory` in the default config (OpenBSD does), and we don’t want unrelated `\.so`files showing up in the “Load Core” menu.

2016-09-04-104842_960x720_scrot

I’m fine with this patch as long as the default is something ending in `/libretro`. Probably `$(prefix)/lib/libretro`, but I really don’t care what as long as it’s something. And upstream retroarch needs to standardize on such a directory, so the same change should be pushed to gambatte and bsnes. Otherwise there will be more divergence over time as more operating systems package libretro cores…

**Comment by bochecha** [comment]
> And upstream retroarch needs to standardize on such a directory, so the same change should be pushed to gambatte and bsnes. Otherwise there will be more divergence over time as more operating systems package libretro cores…

Works for me.

Just one thing, this is the first time I hear about this `libretro_directory`. What does it do? And would it make sense to use this name instead of the `core_installdir` I pulled out of a hat? :smile:

**Comment by bochecha** [comment]
> Just one thing, this is the first time I hear about this libretro_directory. What does it do? And would it make sense to use this name instead of the core_installdir I pulled out of a hat? 

Oh, is it the `LIBRETRO_DIR` variable from the `libretro/Makefile`?

If so, maybe we don't need `core_installdir` at all, and instead we would just install the stuff to `$(DESTDIR)$(prefix)/lib/$(LIBRETRO_DIR)` ?

**Comment by bentley** [comment]
`libretro_directory` is a setting in `~/.config/retroarch/retroarch.cfg` that determines which directory RGUI’s “Load Core” menu starts in.

Of course, like the other 500 or so settings in the default generated RetroArch configuration file, it’s undocumented…

**Comment by bochecha** [comment]
Sorry for dropping the ball on this.

So getting back at it, I've redone this change, dropping the `core_installdir` variable I was introducing, and instead:

* reusing the standard `prefix` and `libdir` variables (as used by the Autotools, and pretty much every other project)
* installing in `$(libdir)/$(LIBRETRO_DIR)`.

Would that work better?

**Comment by rdanbrook** [comment]
It looks good to me. This doesn't introduce anything I see as problematic, but if anyone takes issue with it we can modify it again.

Thanks for putting the effort towards this.

**Pull request merged**
